Reno 2747/press main page
NYPL/dxp-react-search pull request #245
Opened 2022-03-14 20:34 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-2747)
[Metronome](http://themetronome.co/templates/t-149-press-releases-main/)

**This PR does the following:**
- Has Breadcrumbs Home/Press
- Renders list of 10 press releases/ page with title and date
- Renders pagination 
- Renders Media Contacts through press-releases/

### Review Steps:
- [ ] Pull in remote braches `git fetch`
- [ ] Switch to PR branch `git checkout RENO-2747/press-main-page`
- [ ] Make sure you have the latest updates `git pull origin RENO-2747/press-main-page`
- [ ] Start up localhost `npm run dev`

### Front End Review Steps:
- [ ] View [Press Main Page](http://localhost:3000/press)

2022-03-14 20:37 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-14 21:26 UTC, nypl-wluisi requested changes
Overall this looks great! I added a few inline comments for some small tweaks.

2022-03-14 21:26 UTC, nypl-wluisi commented on src/components/press-releases/PressReleasesContainer/PressReleasesContainer.tsx
> +      sx={{
Keep Box here, but move this `sx={{` for centering Pagination so that it wraps the Pagination component, not the entire component.

2022-03-14 21:26 UTC, nypl-wluisi commented on src/components/press-releases/PressReleasesContainer/PressReleaseCard.tsx
> +      <HorizontalRule className="horizontal-rule" />
for HorizontalRule i think you can remove the `className="horizontal-rule”`

2022-03-14 21:26 UTC, nypl-wluisi commented on src/components/press-releases/PressReleasesContainer/PressReleasesContainer.tsx
> +function PressReleaseContainer({
Rename `PressReleaseContainer` → `PressReleaseCollection` for the file names and function names, also the type should then be `PressReleaseCollectionProps` — I used the “container” name on Blog, but I actually don’t like it, so we can update it for press release here and then circle back later and update the Blog components to match.

2022-03-14 21:29 UTC, nypl-wluisi commented
For testing, lets add at least the following scenarios

```
// Check breadcrumbs
it("Breadcrumbs includes page title as last item and is not a link", () => {});

// Check for Hero.
it("Hero should include h1 title", () => {});

// Check for any menus.
it("Right rail menu should be present in sidebar", () => {});

// Check for 10 Press Releases on main page
it("10 press releases should display on first page", () => {});

// Clicking page 3 link in pagination takes user to page 3
// Clicking next link in pagination takes user to page 2
```

Lets also create utility functions for Breadcrumbs and Menu testing 

You can see some existing examples of a testing util functions here: https://github.com/NYPL/dxp-react-search/blob/development/cypress/support/utils.ts

I'd like to start doing these in separate files, so for press release testing, lets do

```
cypress/support/utils/breadcrumbs.ts
cypress/support/utils/menus.ts
```

You can use what you already did for Breadcrumbs and Menus in the individual press pg tests as a starting point, but 
the function should be useable on both press collection pg and press individual pg, and then eventually we can use it on other pages that use breadcrumbs and menus, etc.

2022-03-14 21:30 UTC, nypl-wluisi commented
Also, not directly related to this work, but you should also update `press/[slug].tsx` to use the new Error/404 component. You can see how its done on `blog/[slug].tsx`

2022-03-14 21:34 UTC, nypl-wluisi commented
@isastettler Oh, and just one another note. I pushed 1 commit to this branch to update it with the latest from `development`, so just pull that change in before you start on any additional changes requested here.

2022-03-14 21:37 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-14 23:12 UTC, nypl-wluisi commented on src/components/press-releases/layouts/PageContainer.js
> +        backgroundColor="var(--nypl-colors-ui-gray-light-cool)"
For both of these colors, you shouldn't need the `var()`, could just be `ui.gray.light-cool` and `ui.black`

2022-03-15 15:22 UTC, isastettler commented on src/components/press-releases/layouts/PageContainer.js
> +        backgroundColor="var(--nypl-colors-ui-gray-light-cool)"
for some reason that does not work here...

2022-03-16 19:48 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-17 04:05 UTC, nypl-wluisi requested changes
@isastettler In general, this looks great. Awesome work! Just a few more small changes.

2022-03-17 04:05 UTC, nypl-wluisi commented on src/components/press-releases/layouts/MediaContacts/MediaContacts.tsx
> +function MediaContacts({ mediaContacts }: any) {
Add a line between the imports and the function

2022-03-17 04:05 UTC, nypl-wluisi commented on src/components/press-releases/layouts/PageContainer.js
> +        //backgroundColor needs to be replace with correct variable of DS
Remove this comment

2022-03-17 04:05 UTC, nypl-wluisi commented on cypress/tests/press-releases/press-releases-all.test.js
> +    cy.visit("http://localhost:3000/press/");
We don't need the base path anymore as we set it in `cypress.json` now, so this could be changed to just `cy.visit("/press")`

2022-03-17 16:43 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-17 18:04 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-18 03:58 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-21 18:26 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-22 01:56 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr245-rdim6bbznopitupfspcumolz5npxkyh5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622fa6c6c49d661fdcf41a00

2022-03-22 02:11 UTC, nypl-wluisi requested changes
@isastettler Just one more change and then we'll be good to merge! Also, I've updated this branch with the latest from development, so make sure to pull in the latest changes on this branch before you start.

2022-03-22 02:11 UTC, nypl-wluisi commented on src/components/press-releases/PressReleaseCollection/PressReleaseCollection.tsx
> +    return <ListSkeletonLoader itemsCount={10} />;
I added a new skeleton wrapper component for Blogs: https://github.com/NYPL/dxp-react-search/blob/development/src/components/shared/Card/CardGridSkeletonLoader.tsx

We can use `CardGridSkeletonLoader` here instead of `ListSkeletonLoader`.

You can see how I use it on Blogs: https://github.com/NYPL/dxp-react-search/blob/543194c32d6755855d282c77b5649006b35faf9f/src/components/blogs/BlogsContainer/BlogsContainer.tsx#L172

If you set `showImage` to `false` it should give us the skeleton loader shape we want.

2022-03-22 16:37 UTC, nypl-wluisi commented on src/components/press-releases/PressReleaseCollection/PressReleaseCollection.tsx
> +        orientation="horizontal"
Change to `cardLayout="row"`

2022-03-22 20:11 UTC, merged