Card Grid & Card
NYPL/dxp-react-search pull request #269
Opened 2022-04-14 18:35 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-2901)

**This PR does the following:**
- adds LinkCard and LinkCardGrid Components
- adds chakra styling file for LinkCard and LinkCardGrid
- replaces CardGrid with LinkCardGrid and LinkCard
- adds Discover, From Our Blog, Updates section using LinkCardGrid and LinkCard

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

2022-04-14 20:20 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr269-flv7fqmwqh8frbberjjzgfvqler2js0h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62586972bda4981539f76633

2022-04-18 17:38 UTC, nypl-wluisi commented on src/components/home-v1/LinkCard.tsx
> +  variant?: Variant;
Remove the `Variant` enum and just do union, i.e., 
```ts
variant?: "event-spotlight" | "event-card" | "blog-card" | "updates-card"
```

2022-04-18 17:39 UTC, nypl-wluisi commented on src/components/home-v1/LinkCard.tsx
> +export enum Variant {
See comment on line 25, but we can remove this

2022-04-18 17:44 UTC, nypl-wluisi commented on src/components/home-v1/LinkCardGrid.tsx
> +  variant?: string;
change `string` to a union: `"row-grid" | "column-grid" | "updates-grid"`

2022-04-18 17:47 UTC, nypl-wluisi commented on src/components/home-v1/LinkCard.tsx
> +          tabIndex="-1"
change this to `tabIndex={-1}` and remove the `//@ts-ignore`

2022-04-18 17:53 UTC, nypl-wluisi requested changes
In general this looks great, there's a few inline comments I added. Also, small renaming request for the components:

- Rename `LinkCard` → `Card` (and related props, theme obj, etc)
- Rename `LinkCardGrid` → `CardGrid` (and related props, theme obj, etc)

Move both components to a dir called `CardGrid`

2022-04-19 07:56 UTC, isastettler commented on src/components/home-v1/LinkCard.tsx
> +  variant?: Variant;
I am curious about the reason or if this is a preference?

2022-04-19 08:00 UTC, isastettler commented on src/components/home-v1/LinkCard.tsx
> +          tabIndex="-1"
I made the same change in FeaturedEvents.tsx

2022-04-19 11:18 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr269-flv7fqmwqh8frbberjjzgfvqler2js0h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62586972bda4981539f76633

2022-04-19 15:04 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr269-mkx2j2otv2vuokgazu4cw9bshmywy58a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625ece2bef17c6f5698b0fa2

2022-04-20 16:59 UTC, nypl-wluisi commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr269-mkx2j2otv2vuokgazu4cw9bshmywy58a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625ece2bef17c6f5698b0fa2

2022-04-21 23:36 UTC, nypl-wluisi approved these changes
This looks good! The accessibility related stuff we can follow up with Zach next week. I'm going to merge this now so you can create a new branch off the `RENO-2761/homepg-prototype` branch for the Hero work.

2022-04-21 23:37 UTC, merged