RENO-2916: CardGrid Test
NYPL/dxp-react-search pull request #276
Opened 2022-05-10 17:21 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-2916)

**This PR does the following:**
- add tests for CardGrid.tsx and Card.tsx

### Review Steps:
- [ ] pull in branch `git pull origin RENO-2916/cardgrid-test`
- [ ] run `npm test`

2022-05-11 00:05 UTC, nypl-wluisi requested changes
@isastettler In general looks great, just a few changes.

2022-05-11 00:05 UTC, nypl-wluisi commented on src/components/home-v1/mockContent.js
> +          id: "aurthor-talks-4",
"author"

2022-05-11 00:05 UTC, nypl-wluisi commented on src/components/home-v1/mockContent.js
> +          id: "aurthor-talks-4",
"author"

2022-05-11 00:05 UTC, nypl-wluisi commented on src/components/home-v1/mockContent.js
>            date: "MONDAY–THURSDAY",
For this and other date values, have them here as regular case, so "Monday-Thursday" or "Ongoing" and then cast them to all uppercase using CSS.

2022-05-11 00:05 UTC, nypl-wluisi commented on src/components/home-v1/mockContent.js
>            date: "MONDAY–THURSDAY",
For this and other date values, have them here as regular case, so "Monday-Thursday" or "Ongoing" and then cast them to all uppercase using CSS.

2022-05-11 16:10 UTC, isastettler commented on src/components/home-v1/CardGrid/Card.tsx
> +        <Heading as="h3" aria-describedby={describedByString}>
Oh this is awesome! I tried to do something like that and could not get it to work!!

2022-05-11 16:23 UTC, isastettler commented on src/components/home-v1/mockContent.js
>            date: "MONDAY–THURSDAY",
I changed the data, the css was already set up to change it to all uppercase.

2022-06-29 16:01 UTC, nypl-wluisi commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr276-twuv78uqgl1vjyrw9lfpbypnbndvashs.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627a9f38c4a9adf3431d34f5

2022-06-29 16:07 UTC, nypl-wluisi approved these changes

2022-06-29 16:08 UTC, merged