Reno 3070/whats on code cleanup
NYPL/dxp-react-search pull request #304
Opened 2022-08-24 16:56 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-3070)

**This PR does the following:**
- Fix layout/ style of "What's on" section
- Adds style theme file for "What's on" section (event.ts)
- Clean up of unused code in EventCollection folder

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

2022-08-24 18:31 UTC, nypl-wluisi requested changes
@isastettler In general, this looks great. Just a few change requested inline. Also, you should fix the failing tests. You can see which ones fail by running `npm test`.

2022-08-24 18:31 UTC, nypl-wluisi commented on src/components/home-v1/EventCollection/EventCard.tsx
> +  const styles: any = useStyleConfig("Event", { variant, size });
Add a line between this const and the return

2022-08-24 18:31 UTC, nypl-wluisi commented on src/components/home-v1/EventCollection/EventCollection.tsx
> +  const setCategoryTitle = (category: string) => {
Rename `setCategoryTitle` → `eventCategoryLabel`

2022-08-24 18:31 UTC, nypl-wluisi commented on src/components/home-v1/EventCollection/EventCollection.tsx
> +      default:
For consistency, I would also add cases for "exhibitions" and "other" as well

2022-08-24 18:31 UTC, nypl-wluisi commented on src/components/home-v1/EventCollection/EventCollection.tsx
> +                if (event.weight === 0) {
Instead of `event.weight === 0` we should just get the first item in the array. This might not always be 0, as they could do weights like "10, 20, 30, 40", etc.

2022-08-25 09:15 UTC, isastettler commented on src/components/home-v1/EventCollection/EventCollection.tsx
> +                if (event.weight === 0) {
When I tried to implement it this way I noticed that in this file the event item arrays are not sorted yet. So when I changed it, on mobile the wrong event showed up. We could sort all arrays already in this file if you think that would be the better solution? Right now the item arrays get sorted in EventCollectionTabPanelContent.tsx

2022-08-26 15:20 UTC, nypl-wluisi approved these changes
Looks great

2022-08-26 15:20 UTC, merged