RENO-3178 alphabetFilter Component
NYPL/dxp-react-search pull request #345
Opened 2022-11-06 22:48 UTC by misselbeck

[Jira Ticket](https://jira.nypl.org/browse/RENO-3178)
[Metronome](http://themetronome.co/components/XXX/?fresh=true)

**This PR does the following:**
- Upgrades to the Design System v.1.2.0
- Implements the alphabetFilter component on Articles and Databases

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

2022-11-08 00:26 UTC, nypl-wluisi requested changes
@misselbeck This looks pretty good, just a few changes.

2022-11-08 00:26 UTC, nypl-wluisi commented on src/components/online-resources/AlphabetNav/AlphabetNav.js
> +  function alphaLink(link) {
Rename this to `handleClick`. And instead of window.location we should use `router.push` from NextJS, so something like this:

```jsx
const handleClick = (link) => {  
  if (link === "showAll") {
    router.push(`${ONLINE_RESOURCES_BASE_PATH}/search?alpha=all`);
  } else {
    router.push(`${ONLINE_RESOURCES_BASE_PATH}/search?alpha=${link.toUpperCase()}`)l
  }
}
```

You can read more about this here: https://nextjs.org/docs/api-reference/next/router#userouter

2022-11-08 00:26 UTC, nypl-wluisi commented on src/components/online-resources/AlphabetNav/AlphabetNav.js
> +        className={`${s.AlphabetNav} ${className ? className : ""}`}
I would remove the className prop and also the `AlphabetNav.module.css` file. The margin style can be applied here by wrapping in a Box, or just adding the style prop directly to `AlphabetFilter`

2022-11-13 23:34 UTC, misselbeck commented on src/components/online-resources/AlphabetNav/AlphabetNav.js
> +  function alphaLink(link) {
I made this change and reviewed the documentation that you linked.

2022-11-13 23:39 UTC, misselbeck commented on src/components/online-resources/AlphabetNav/AlphabetNav.js
> +        className={`${s.AlphabetNav} ${className ? className : ""}`}
I removed the style css in favor of the `<Box>` component.

As for the className, I believe it is still needed as it is referenced in the `SearchResults` component (which adds a border bottom when the AlphabetFilter is displayed in that context.

![nypl-search-result-alphabet-nav](https://user-images.githubusercontent.com/1325185/201550493-40ac59bf-2826-4235-bc01-4663d0c31fc2.jpg)

Let me know if you'd like to handle that in a different way.

2022-12-06 22:52 UTC, nypl-wluisi requested changes
@misselbeck This looks good, but a few things.
- the package-lock.json file is missing ? Can you add it to this PR? Also, make sure you're using node `v16.15.0` and npm `8.5.5` which can be installed with nvm
- There's new warnings flooding the console from the 1.2 version of the DS. I added a ticket here for that work and assigned to you: https://jira.nypl.org/browse/RENO-3306 -- up to you if you want to commit here or do a separate PR.

2022-12-07 04:00 UTC, nypl-wluisi commented
@misselbeck Can you also resolve the merge conflict with development?

2022-12-08 00:30 UTC, nypl-wluisi approved these changes
Looks great. Awesome work here!

2022-12-08 00:30 UTC, merged