Reno 3517/donor credit
NYPL/dxp-react-search pull request #413
Opened 2023-04-26 15:12 UTC by aarnold101

[Jira Ticket](https://jira.nypl.org/browse/RENO-3517)
[Figma Design](https://www.figma.com/file/rNUgLS3jwsGcC8vpLdzq0Q/Donor-Credit?node-id=1879-31959&t=M5MfJl1A8wUnVUJl-0)

## **This PR does the following:**

- Adds Donor Credit component to Section Front component
- Uses data from a multidev where the Donor Credit field has been added to the Section Front UI

### Review Steps:

- [ ] Pull in branch `git fetch origin RENO-3517/donor credit`
- [ ] Switch to relevant brach `git checkout RENO-3517/donor credit`
- [ ] Change line 3 in .env file: DRUPAL_API=https://pr1054-nypl1.pantheonsite.io
- [ ] Start a local build `npm run build && npm start`
- [ ] Confirm tests are passing `npm test`

### Front End Review Steps:

- [ ] View [donor credit at the bottom of the page](http://localhost:3000/education/educators)

2023-04-27 14:17 UTC, isastettler requested changes
This looks good, I added comments for a few changes.

2023-04-27 14:17 UTC, isastettler commented on src/apollo/server/type-defs/sectionFront.js
> +    donorCredit: DonorCredit
Let's rename `donorCredit to `bottomContent`.
We will also change the type of this property to be a `union` similar to the featuredContent. In our case for now this union will only hold the DonorCredit type. 

Add the `union SectionFrontBottomContent = DonorCredit` under the `union SectionFrontMainContent` line and replace the `DonorCredit` type on line 12 with `[SectionFrontBottomContent]`.

2023-04-27 14:17 UTC, isastettler commented on src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
> +      donorCredit {
Now that we receive the data as an array under the property of `bottomContent` we will have to update our query too. Replace our current query with `bottomContent { ... on DonorCredit { __typename
          id
          heading
          description
          showBorder} }`

2023-04-27 14:17 UTC, isastettler commented on src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
> +          {sectionFront.donorCredit && Components(sectionFront.donorCredit)}
Lets move the new bottomContent section to the `bottomContent` prop of the `<PageContainer/>` component. We will also have to use the `.map()` method on the `sectionFront.bottomContent` since we are working with an array now. The new code block will look like this:
`contentBottom={
        sectionFront.bottomContent &&
        sectionFront.bottomContent.map(
          (contentComponent: { [key: string]: any }) =>
            Components(contentComponent)
        )
      }`

2023-04-27 14:17 UTC, isastettler commented on src/components/shared/DonorCredit/DonorCredit.tsx
> +    <Flex id={`donor-credit-${id}`} marginY="xl" flexDirection="column">
Since we are passing the component now in a different section of the `PageContainer` we will have to adjust the styling slightly. Change the `marginY` prop of the `<Flex>` component to a `marginBottom`. This should fix it.

2023-04-27 14:17 UTC, isastettler commented on src/components/shared/DonorCredit/DonorCredit.test.tsx
> +  it("should render the UI snapshot correctly", () => {
Since we are making changes to the DonorCredit component most likely the snapshots test will fail after the update. We can update the snapshot tests for a specific test unit by running `npm test DonorCredit -- --updateSnapshot`

2023-04-28 21:06 UTC, nypl-wluisi requested changes
Looks great, one small change.

2023-04-28 21:06 UTC, nypl-wluisi commented on src/components/shared/DonorCredit/DonorCredit.tsx
> +function DonorCredit({
You can change this to `export default function DonorCredit` and then remove the last line of `export default DonorCredit;`

2023-05-09 15:22 UTC, nypl-wluisi approved these changes

2023-05-09 15:24 UTC, merged