RENO-3536: Wires Up Breadcrumbs from Drupal JSON API.
NYPL/dxp-react-search pull request #415
Opened 2023-05-01 19:59 UTC by aarnold101

[Jira Ticket](https://jira.nypl.org/browse/RENO-3536)

## **This PR does the following:**

- Adds schema type for breadcrumbs
- Adds breadcrumbs to sectionfront resolver
- Passes sectionFront.breadcrumbs.data to page container component

### Review Steps:

- [ ] Pull in branch `git fetch origin RENO-3536/wire-up-breadcrumb-data`
- [ ] Switch to relevant brach `git checkout RENO-3536/wire-up-breadcrumb-data`
- [ ] Change .env line 3: `DRUPAL_API=https://pr1057-nypl1.pantheonsite.io`
- [ ] Start a local build `npm run build && npm start`
- [ ] Confirm tests are passing `npm test`

### Front End Review Steps:

- [ ] View [Example](http://localhost:3000/eduction/educators)

2023-05-02 21:34 UTC, nypl-wluisi requested changes
@aarnold101 @jberube-nypl @isastettler Looks good, just a few small changes. Also, I updated this branch w/ latest from development, so make sure to pull in latest changes on this PR branch first.

2023-05-02 21:34 UTC, nypl-wluisi commented on src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
> +      breadcrumbs {
You don't actually need the `... on` and it can be done simplier as

```
breadcrumbs {
  id
  title
  url
}
```

2023-05-02 21:34 UTC, nypl-wluisi commented on src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
> +      breadcrumbs={sectionFront.breadcrumbs.map(
You can do this like this and remove the `any`

```tsx
breadcrumbs={sectionFront.breadcrumbs.map(
  (breadcrumbsItem: {
    id: string;
    title: string;
    url: string;
  }): BreadcrumbsItem => {
    return {
      text: breadcrumbsItem.title,
      url: breadcrumbsItem.url,
    };
  }
)}
```

2023-05-03 16:59 UTC, aarnold101 commented on src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
> +      breadcrumbs {
Done

2023-05-09 15:34 UTC, merged