RENO-37373: Update Homepage Card
NYPL/dxp-react-search pull request #464
Opened 2023-12-07 10:11 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-3737)

## **This PR does the following:**

*I made this a Draft PR because I am wondering if it would be better to remove bold and italic options from the card text options in Drupal.* 
- Remove DS `Text` component for card description and pass the description to the Chakra `Box` component through `dangerouslySetInnerHTML` prop
- pass the `Box` component the `as='p"` prop to ensure the description text is rendered in a paragraph html tag

### Review Steps:

- [ ] Pull in branch `git fetch origin RENO-3737/fix-homepage-blog-card-bug`
- [ ] Switch to relevant brach `git checkout RENO-3737/fix-homepage-blog-card-bug`
- [ ] Start a local build `npm run build && npm start`
- [ ] Confirm unit tests are passing `npm test`
- [ ] Confirm cypress tests are passing `npm run build && npm start` and `npm run cypress` in separate terminals

### Front End Review Steps:

- [ ] View [Example](http://localhost:3000/)

2023-12-13 01:48 UTC, nypl-wluisi requested changes
@isastettler Looks good, a few small changes

2023-12-13 01:48 UTC, nypl-wluisi commented on src/components/home-v1/CardGrid/Card.tsx
> +        ></Box>
Change `/>` and remove the `</Box>`

2023-12-13 01:48 UTC, nypl-wluisi commented on src/components/home-v1/CardGrid/Card.tsx
> +          as="p"
Also, probably safer to just do this as a `div`, so you can remove the `as="p"` -- since `<p>` tags could be in the html returned from drupal.

2023-12-15 17:50 UTC, isastettler commented on src/components/home-v1/CardGrid/Card.tsx
> +          as="p"
good catch! Fixed it.

2023-12-18 21:08 UTC, nypl-wluisi approved these changes

2023-12-18 21:09 UTC, merged