RENO-3736: Fix Blog LinkCard padding
NYPL/dxp-react-search pull request #470
Opened 2023-12-22 17:23 UTC by isastettler

[Jira Ticket](https://jira.nypl.org/browse/RENO-3736)

## **This PR does the following:**

- Adds a new prop called `isBlog` to TextFormatted component
- Adds a conditional `marginBottom="l"` to TextFormatted when `isBlog` is true
- passes `isBlog` to TextFormatted in CardList

### Review Steps:

- [ ] Pull in branch `git fetch origin RENO-3736/fix-blog-bug-padding-link-card`
- [ ] Switch to relevant brach `git checkout RENO-3736/fix-blog-bug-padding-link-card`
- [ ] Start a local build `npm run build && npm start`
- [ ] Confirm unit tests are passing `npm test`
- [ ] Confirm cypress tests are passing `npm run build && npm start` and `npm run cypress` in separate terminals

### Front End Review Steps:

- [ ] View [Example Blog](http://localhost:3000//blog/2020/05/29/manhattanhenge-reading-list)
- [ ] Confirm that the CardList description has a marginBottom
- [ ] View[Example Section Front](http://localhost:3000/education)
- [ ] Confirm there is no extra `marginBottom` applied to description texts

2024-01-04 19:41 UTC, nypl-wluisi requested changes

2024-01-04 19:41 UTC, nypl-wluisi commented on src/components/shared/ContentComponents/CardList.tsx
> +      {description && <TextFormatted html={description} isBlog />}
I would remove the `isBlog` prop and just wrap `TextFormatted` like this:

```jsx
<Box mb="l">
  <TextFormatted html={description} />
</Box>
```

2024-01-05 15:53 UTC, nypl-wluisi requested changes
@isastettler Looks good, just 1 more small change.

2024-01-05 15:53 UTC, nypl-wluisi commented on src/components/shared/TextFormatted/TextFormatted.tsx
> +  console.log("formattedText used!");
Remove the `console.log`

2024-01-05 16:27 UTC, isastettler commented on src/components/shared/TextFormatted/TextFormatted.tsx
> +  console.log("formattedText used!");
Thanks for catching this.

2024-01-05 16:30 UTC, merged