Reno 4082/cypress update
NYPL/dxp-react-search pull request #531
Opened 2024-07-16 19:59 UTC by aarnold101

Fix breadcrumbs test
Fix Articles & Databases JSTOR link test
Add A&D alphabet filters tests
Fix Secondary Nav modal test

[Jira Ticket](https://jira.nypl.org/browse/RENO-4082)

2024-07-18 14:10 UTC, isastettler requested changes
Looks good. There are few changes I would recommend.
A general note: The PR Github templet should makes it easier for the RR reviewer to get the branch set up locally and hopefully it is easy to complete for the PR creator too (for future PRs).

2024-07-18 14:10 UTC, isastettler commented on cypress/tests/articles-databases/articles-databases.test.js
> -      name: /we're sorry \.\.\./i,
If you search the code base for "we're sorry" you will find the `_error` file where the text for 404 errors is set. This is a actual bug in the app and we should keep the tests as is as the tests are correct.

2024-07-18 14:10 UTC, isastettler commented on cypress/tests/articles-databases/articles-databases.test.js
> +      name: /error!/i,
Same here.

2024-07-18 14:10 UTC, isastettler commented on cypress/tests/blogs/blog-post.test.js
> +      name: /error!/i,
Same here.

2024-07-22 20:31 UTC, aarnold101 commented on cypress/tests/articles-databases/articles-databases-main.test.js
> -  it("Most popular links take user to correct page", () => {
Restored to one test, with updated description.

2024-07-22 20:31 UTC, aarnold101 commented on cypress/tests/articles-databases/articles-databases.test.js
> -      name: /we're sorry \.\.\./i,
Restored.

2024-07-22 20:31 UTC, aarnold101 commented on cypress/tests/articles-databases/articles-databases.test.js
> +      name: /error!/i,
Restored.

2024-07-22 20:31 UTC, aarnold101 commented on cypress/tests/blogs/blog-post.test.js
> +      name: /error!/i,
Restored.

2024-07-31 13:12 UTC, isastettler requested changes
Other than the last small change this looks good to me.

2024-07-31 13:12 UTC, isastettler commented on cypress/tests/articles-databases/articles-databases-main.test.js
> +  it("Alphabet navigation takes user to correct page", () => {
After talking to Bill this should be removed as it is not part of the ticket scope.

2024-07-31 21:16 UTC, aarnold101 commented on cypress/tests/articles-databases/articles-databases-main.test.js
> +  it("Alphabet navigation takes user to correct page", () => {
Done.

2024-07-31 21:18 UTC, aarnold101 commented
I was able to restore the "Accessibility Test: renders an 'aria-expanded' on toggle buttons of nested menu items" test by changing the URL being used for the test. Prior to the latest commit I had to comment it out b/c the previous URL did not have tertiary navigation.

2024-08-08 16:31 UTC, isastettler requested changes
You got the issue right! One small change I would make.

2024-08-08 16:31 UTC, isastettler commented on cypress/support/utils/testBreadcrumbs.ts
> +    updatedText = updatedText.substring(0, 39);
Instead of doing this you can use `.trim()` to remove any trailing white space. And you can chain it like this: 
`updatedText.substring(0, 39).trim() + "...";`
Otherwise this looks good now. 

Nit: I might name it `updatedTitle` or even `finalTitle` rather than `updatedText` as it's getting the value from the `title` prop.

2024-08-08 20:30 UTC, aarnold101 commented on cypress/support/utils/testBreadcrumbs.ts
> +    updatedText = updatedText.substring(0, 39);
I changed the var name to `breadcrumbTitle` for better readability.

Lines 6 & 7 (basically) match the code of the [DS truncate function](https://github.com/NYPL/nypl-design-system/blob/4581b57b83a2aecab87cb1486148036cf3c03903/src/utils/utils.ts#L143). Using `.trim` would introduce a problem of cutting off words, I think. For example "This Title Has More Than Forty Characters" would become "This Title Has More Than Forty Character..." and fail the test.

2024-08-08 20:40 UTC, isastettler commented on cypress/support/utils/testBreadcrumbs.ts
> +    updatedText = updatedText.substring(0, 39);
OK so now I saw that they truncate only if the title is bigger than 40. I should have seen that earlier, but you will want to remove the `=` from the if statement. See this line in the[ Design System](https://github.com/NYPL/nypl-design-system/blob/4581b57b83a2aecab87cb1486148036cf3c03903/src/components/Breadcrumbs/Breadcrumbs.tsx#L59)

2024-08-09 15:59 UTC, aarnold101 commented on cypress/support/utils/testBreadcrumbs.ts
> +    updatedText = updatedText.substring(0, 39);
Removed `=`.

2024-08-14 13:42 UTC, isastettler approved these changes
This looks good to me now.

2024-08-29 15:18 UTC, merged