RENO-1708: Set Unqiue Asset Prefix for Reverse Proxy
NYPL/dxp-react-search pull request #60
Opened 2020-09-14 19:27 UTC by nypl-wluisi

[Jira Ticket](http://jira.nypl.org/browse/RENO-XXX)

**This PR does the following:**
- Adds `ASSET_PREFIX` .env variable
- Wires up `ASSET_PREFIX` to next.config.js

** Local Dev, Local Dev in Production Mode, QA AWS Env **
ASSET_PREFIX would not be used

** AWS PROD **
We are always running a RP here, so ASSET_PREFIX would be `/scout`

** AWS QA (When Testing RP Rules)
ASSET_PREFIX would be `/scout` -- manually set on AWS admin/console ?

### Review Steps:
- [ ] Review logic of the .env variable above

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

2020-09-15 15:38 UTC, gkallenberg requested changes
Just a little change. Let me know if that doesn't make sense.

2020-09-15 15:38 UTC, gkallenberg commented on provisioning/set-env
> +  ASSET_PREFIX=''
We don't need to set this as something different for deployment to QA since both RP location blocks will need to do the same kind of routing. The qa-www.nypl.org domain is still proxied. Plus we need to test whether the changes suggested on that blog post will work on the QA RP before moving to production. You can remove this line, and can document what the asset prefix is for in the README.

2020-09-15 16:07 UTC, nypl-wluisi commented on provisioning/set-env
> +  ASSET_PREFIX=''
I removed this line and updated the readme.md with a new section on the asset prefix logic.

2020-09-15 19:39 UTC, gkallenberg approved these changes

2020-09-15 20:03 UTC, EdwinGuzman approved these changes

2020-09-30 16:16 UTC, nypl-wluisi commented
@gkallenberg So I did some tests locally, and using "scout" or whatever for the `assetPrefix` and `rewrites()` mostly works, but actually breaks the "hot reloading" in dev mode (i.e., when you make a change to the code, the browser will automatically pick up the change). 

However, using a blank string for `ASSET_PREFIX` and the `rewrites()` source path  fixes the problem, which we'd only do locally anyway.

2020-09-30 18:11 UTC, EdwinGuzman commented
I have forgotten why this was needed since we last talked, but is it because more nextjs apps _might_ make requests to `/next/....`?

The locations app works fine in RP so I'm just wondering is this is needed for this app or is a safety check for other apps in the `nypl.org` domain?

2020-09-30 18:17 UTC, gkallenberg approved these changes

2020-10-20 16:28 UTC, merged