RENO-1775:
NYPL/dxp-react-search pull request #80
Opened 2020-11-07 01:52 UTC by nypl-wluisi

[Jira Ticket](http://jira.nypl.org/browse/RENO-XXX)

**This PR does the following:**
-

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

2020-12-02 19:40 UTC, nypl-wluisi commented on src/utils/setTodaysHours.js
> +          const closingStartHours = dayjs(alert.applies.start).format('HH:mm');
Might need to include the tz method here: `.tz('America/New_York')` -- test locally by changing the timezone of your computer.

2020-12-03 15:52 UTC, nypl-wluisi commented on src/utils/setTodaysHours.js
> +          const closingStartHours = dayjs(alert.applies.start).format('HH:mm');
Try setting a global timezone for all dayjs

`dayjs.tz.setDefault("America/New_York")`

https://day.js.org/docs/en/timezone/set-default-timezone

2020-12-08 20:34 UTC, jberube-nypl requested changes

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsTempClosingOne, true)
Remove third param

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsTempClosingMany, true)
remove third param

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsHoursMins, true)
remove third param

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:05:00-04:00', alertsHoursMinsActive, true)
remove third param

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/naturalSort.test.js
> +    console.log(timesNaturalSort);
remove

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/setTodaysHours.js
> + * @param {object} alerts - an object of alerts & closings data.
@param {array} alerts - an array of alert objects containing alert info & closings data.

2020-12-08 20:34 UTC, jberube-nypl commented on src/utils/setTodaysHours.js
> +    alerts.some(alert => {
alerts.forEach(alert => {

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/filterByOpenNow.js
>    return locations.reduce((accumlator, location) => {
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.js
>    } else {
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/filterByOpenNow.js
> +    const isActiveClosing = hasActiveClosing(today, location._embedded.alerts, location.open);
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsTempClosingOne, true)
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsTempClosingMany, true)
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:00:00-04:00', alertsHoursMins, true)
This is fixed.

2020-12-08 22:20 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.test.js
> +      hasActiveClosing('2020-10-27T12:05:00-04:00', alertsHoursMinsActive, true)
This is fixed.

2020-12-08 22:21 UTC, nypl-wluisi commented on src/utils/naturalSort.test.js
> +    console.log(timesNaturalSort);
This is fixed.

2020-12-08 22:21 UTC, nypl-wluisi commented on src/utils/setTodaysHours.js
> + * @param {object} alerts - an object of alerts & closings data.
This is fixed.

2020-12-08 22:21 UTC, nypl-wluisi commented on src/utils/setTodaysHours.js
> +    alerts.some(alert => {
This is fixed.

2020-12-08 22:37 UTC, jberube-nypl requested changes

2020-12-08 22:37 UTC, jberube-nypl commented on src/utils/hasActiveClosing.js
>   * @param {object} alerts - an object of alerts & closings data.
* @param {array} alerts - an array of alert objects containing alert info & closings data.

2020-12-08 22:37 UTC, jberube-nypl commented on src/utils/hasActiveClosing.js
>      alerts.map(alert => {
alerts.forEach(alert => {

2020-12-08 23:44 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.js
>   * @param {object} alerts - an object of alerts & closings data.
This is fixed.

2020-12-08 23:44 UTC, nypl-wluisi commented on src/utils/hasActiveClosing.js
>      alerts.map(alert => {
This is fixed.

2020-12-08 23:46 UTC, jberube-nypl approved these changes

2020-12-08 23:48 UTC, merged